
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    expose:
      - "8000"
    # ports:
    #   - "8000:8000"
    env_file:
      - ./server/.env
    restart: always

  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   container_name: web
  #   expose:
  #     - "3000" 
  #   # ports:
  #   #   - "3000:3000"
  #   env_file:
  #     - ./web/.env
  #   restart: always
  #   depends_on:
  #     - server

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      # - web
      - server
    restart: always
